version: 0.2

env:
  variables:
    LIBNAME: "databaseUpgrader"
    MAJOR_VERSION: "1"
    GROUP_ID: "database"
phases:
  pre_build:
    commands:
      - echo $LIBNAME
      - export BUILD_NUMBER="$(curl -s https://pfg5vswacc.execute-api.us-east-1.amazonaws.com/prod/buildnumber/$LIBNAME)"
  build:
    commands:
      - mvn package
      - export VERSION=$MAJOR_VERSION.$BUILD_NUMBER
      - export ARTIFACT=$LIBNAME-$VERSION.jar
      - mv ./target/*.jar ./$ARTIFACT
  post_build:
    commands:
      - aws s3 cp $ARTIFACT s3://com.omegasixcloud.artifacts/$GROUP_ID/$LIBNAME/$VERSION/$ARTIFACT
      - aws s3 cp pom.xml s3://com.omegasixcloud.artifacts/$GROUP_ID/$LIBNAME/$VERSION/pom.xml