version: 0.2

env:
  variables:
    LIBNAME: "DatabaseUpgrader"
    MAJOR_VERSION: "1"
phases:
  pre_build:
    commands:
      - echo $LIBNAME
      - export BUILD_NUMBER="$(curl -s https://pfg5vswacc.execute-api.us-east-1.amazonaws.com/prod/buildnumber/$LIBNAME)"
  build:
    commands:
      - mvn package
      - export ARTIFACT=$LIBNAME-$MAJOR_VERSION.$BUILD_NUMBER.jar
      - mv ./target/*.jar ./$ARTIFACT
  post_build:
    commands:
      - aws s3 cp $ARTIFACT s3://com.omegasixcloud.artifacts/$LIBNAME/$ARTIFACT
artifacts:
  files:
    - ARTIFACT